### ISSUE TITLE
Memory pak partially working

### ISSUE THREAD

**Issue by RigoHoward** [Element18592/N64-FRAM-Memory-Pak#1]
Hello, first of all many thanks for sharing the gerbers and detailed BOM on how build a "last long" DIY memory pak for N64.

I sourced every item (boards from jlcpcb, resistors, cap and fm28v020-sg ic)

I soldered everything in place, fire up perfect dark and i got the corrupted memory message. I attempted to repair the save data and it was ok.

Then i checked if the data was saved (after a few minutes) and it was there.
I fired up doom64 and mortal kombat 4 games and both show me an error regarding memory pak and both dont let me save at all.

So annoyingly the only game which it seems to be saving ok its perfect dark.

i already soldered 2 of this memory packs, one with the ramtron brand ic and another with cypress brand (same specs)

The both memory paks have the same behavior.
So there is any fix which its needed on the board?

Thank you again for doing this possible.

**Comment by Element18592** [comment]
> Hello, first of all many thanks for sharing the gerbers and detailed BOM on how build a "last long" DIY memory pak for N64.
> 
> I sourced every item (boards from jlcpcb, resistors, cap and fm28v020-sg ic)
> 
> I soldered everything in place, fire up perfect dark and i got the corrupted memory message. I attempted to repair the save data and it was ok.
> 
> Then i checked if the data was saved (after a few minutes) and it was there. I fired up doom64 and mortal kombat 4 games and both show me an error regarding memory pak and both dont let me save at all.
> 
> So annoyingly the only game which it seems to be saving ok its perfect dark.
> 
> i already soldered 2 of this memory packs, one with the ramtron brand ic and another with cypress brand (same specs)
> 
> The both memory paks have the same behavior. So there is any fix which its needed on thr board?
> 
> Thank you again for doing this possible.

I haven't tested beyond Perfect Dark. Initially I got the normal repair save data message on first use, repaired it and saved a few times with Perfect Dark and verified the save was still okay and called it a wrap. This is something I made for fun and went based on the OEM board schematics so it should work but I'll have another look into it when I get some free time. Thanks for bringing it to my attention.

**Comment by RigoHoward** [comment]
Hey thanks for your fast reply :)

I can report an update:
I notice the memory pak also works with hybrid heaven, but if you save on that game it will overwrite the perfect dark save.
On Quake 64 you can see the contents of the memory pak, but you cannot save.
On Mortal Kombat 4 a "memory pak exchanged" message its shown when you try to save

**Comment by WilliamDingler** [comment]
I have experienced similar issues.

**Comment by jago85** [comment]
Hi,
I've found this project today and had a look at the gerber data. My viewer has some problems, but I noticed a few things that could cause this issue. I'm not 100% sure, but maybe this is of some help for you:

- Pin 28 of U1 (VCC) is NOT connected to the supply voltage (only to a cap to GND)
- Pin 18 of the edge connector (CE) is only connected to a pull down resistor and thus has absolutely no effect (the chip enable logic is completely ignored)
- Pin 19 of the edge connector (A15) is used as /CE (which might be fine)
- as far as I can tell, the original board uses CE and A15 to generate the /CE for the SRAM (CE must be high and A15 must be low)

**Comment by Element18592** [comment]
Thanks for sharing that. I did notice some of these issues as well. I changed the design layout before pushing it to look a bit better on the eye and I completely forgot to add back a few critical traces when I rearranged a few things. I've got the hopefully fixed boards here and have had them for some time I just haven't had the time to sit down and put them together and test them but hopefully I can do that sometime next week.

**Comment by Retrofletch** [comment]
The available gerbers are the "non-fixed" ones then i assume?

**Comment by WilliamDingler** [comment]
Yes, they are the non-fixed ones.

**Comment by breyell** [comment]
@Element18592 Did you ever get around to checking the fixed boards? Would love to order some but seems like the existing design has issues.

**Comment by Element18592** [comment]
> 

I completely forgot about it until I got your message. I assembled one up and everything is working fine on my end. I made sure to test the problem games people mentioned above and all of them save and load just fine for me. Below is a screenshot of  some of the games tested after wiping it and saving again. I'll go ahead and replace the gerbers now.

![4kosZRE](https://user-images.githubusercontent.com/40620345/195842899-4438cd6b-208a-4b46-b8bc-3da3c7eaac52.jpg)

**Comment by breyell** [comment]
Wow, talk about a quick turnaround. Thanks a bunch for all of your work.

**Comment by RigoHoward** [comment]
Glad to read the update :)
@Element18592

I saw you update the gerbers, the current source its the fixed one?
Thank you in advance ;)

**Comment by Element18592** [comment]
> 
Yes

**Comment by Element18592** [comment]
> Glad to read the update :) @Element18592
> 
> I saw you update the gerbers, the current source its the fixed one? Thank you in advance ;)

Yes

**Comment by RigoHoward** [comment]
Nice!, i compared the older boards i had and after cutting 1 trace and also adding 2 jumper wires, now my fram memory pak its saving with all the games i tested!

@Element18592 @jago85 thanks guys :)

I will share a picture of the modded board when i get home

**Comment by RigoHoward** [comment]
And here it is:

![IMG_20221017_121209](https://user-images.githubusercontent.com/14918085/196215349-aec5679e-d663-497b-a227-f7a63462a6d9.jpg)
